version: '3.8'
services:
  python-api:
    build: ./backend/python
    ports:
      - "8000:8000"
    networks:
      - app-net
  java-api:
    build: ./backend/java-spring
    ports:
      - "8080:8080"
    networks:
      - app-net
  frontend:
    build: ./frontend/vue
    ports:
      - "3000:3000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
